In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
#import csv
csv_file = "ramen-ratings.csv"

In [3]:
#store as dataframe
ramen_df = pd.read_csv(csv_file)

FileNotFoundError: [Errno 2] File b'ramen-ratings.csv' does not exist: b'ramen-ratings.csv'

In [5]:
ramen_df.head()

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN

In [6]:
ramen_df2 = ramen_df[["Country", "Brand", "Variety", "Stars"]]
ramen_df2.head()

,Country,Brand,Variety,Stars
0,Japan,New Touch,T's Restaurant Tantanmen,3.75
1,Taiwan,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,1
2,USA,Nissin,Cup Noodles Chicken Vegetable,2.25
3,Taiwan,Wei Lih,GGE Ramen Snack Tomato Flavor,2.75
4,India,Ching's Secret,Singapore Curry,3.75

In [7]:
ramen_df2.dtypes

Country    object
Brand      object
Variety    object
Stars      object
dtype: object

In [8]:
ramen_df2 = ramen_df2.replace({"United States": "USA", "Dubai": "United Arab Emirates", "Holland":"Netherlands", "Hong Kong": "Hong Kong S.A.R., China", "UK": "United Kingdom","Taiwan": "Taiwan Province of China", "Sarawak":"Malaysia"})
ramen_df2 =ramen_df2.loc[ramen_df2['Country']!='Fiji']

In [9]:
ramen_df3 =ramen_df2.loc[ramen_df2['Stars']!='Unrated']

ramen_df3.head()

,Country,Brand,Variety,Stars
0,Japan,New Touch,T's Restaurant Tantanmen,3.75
1,Taiwan Province of China,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,1
2,USA,Nissin,Cup Noodles Chicken Vegetable,2.25
3,Taiwan Province of China,Wei Lih,GGE Ramen Snack Tomato Flavor,2.75
4,India,Ching's Secret,Singapore Curry,3.75

In [10]:
ramen_df3['Stars'] = ramen_df3['Stars'].astype(float)
ramen_df3.dtypes

/usr/local/lib/python3.6/dist-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

Country     object
Brand       object
Variety     object
Stars      float64
dtype: object

In [11]:
sortedramen_df = ramen_df3.sort_values(['Stars'], ascending=False).reset_index(drop=True)
sortedramen_df.head()

,Country,Brand,Variety,Stars
0,Singapore,Koka,Spicy Black Pepper,5.0
1,South Korea,HoMyeonDang,Premuim Noodle House Crab Jjampong,5.0
2,Taiwan Province of China,Jingqi,Black Eyes Bean Cyanobacteria Noodle With Ging...,5.0
3,Malaysia,Mamee,Chef Gold Recipe Mi Kari Seribu Rasa,5.0
4,Taiwan Province of China,A-Sha Dry Noodle,Chow Mein Original Flavor,5.0

In [12]:
# sortedramen_df.describe

In [13]:
grouped_country = pd.DataFrame(ramen_df3.groupby(["Country"])["Stars"].mean())

grouped_country.sort_values('Stars').head()

                   Stars
Country
Nigeria         1.500000
Canada          2.243902
Netherlands     2.710526
United Kingdom  2.997101
Pakistan        3.000000

In [14]:
#import csv
csv_file2 = "happiness2017.csv"

In [15]:
#store as dataframe
happiness_df = pd.read_csv(csv_file2)
happiness_df.head()

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

In [16]:
new_happiness_df = happiness_df[["Country", "Happiness.Rank", "Happiness.Score", "Economy..GDP.per.Capita.", "Health..Life.Expectancy.", "Freedom"]].copy()
new_happiness_df

,Country,Happiness.Rank,Happiness.Score,Economy..GDP.per.Capita.,Health..Life.Expectancy.,Freedom
0,Norway,1,7.537,1.616463,0.796667,0.635423
1,Denmark,2,7.522,1.482383,0.792566,0.626007
2,Iceland,3,7.504,1.480633,0.833552,0.627163
3,Switzerland,4,7.494,1.564980,0.858131,0.620071
4,Finland,5,7.469,1.443572,0.809158,0.617951
5,Netherlands,6,7.377,1.503945,0.810696,0.585384
6,Canada,7,7.316,1.479204,0.834558,0.611101
7,New Zealand,8,7.314,1.405706,0.816760,0.614062
8,Sweden,9,7.284,1.494387,0.830875,0.612924
9,Australia,10,7.284,1.484415,0.843887,0.601607
10,Israel,11,7.213,1.375382,0.838404,0.405989
11,Costa Rica,12,7.079,1.109706,0.759509,0.580132
12,Austria,13,7.006,1.487097,0.815328,0.567766
13,United States,14,6.993,1.546259,0.774287,0.505741
14,Ireland,15,6.977,1.535707,0.809783,0.573110
15,Germany,16,6.951,1.487923,0.798951,0.562511
16,Belgium,17,6.891,1.463781,0.818092,0.539771
17,Luxembourg,18,6.863,1.741944,0.845089,0.596628
18,United Kingdom,19,6.714,1.441634,0.805336,0.508190
19,Chile,20,6.652,1.252785,0.819480,0.376895
20,United Arab Emirates,21,6.648,1.626343,0.726798,0.608345
21,Brazil,22,6.635,1.107353,0.616552,0.437454
22,Czech Republic,23,6.609,1.352682,0.754444,0.490946
23,Argentina,24,6.599,1.185295,0.695137,0.494519
24,Mexico,25,6.578,1.153184,0.709979,0.412730
25,Singapore,26,6.572,1.692278,0.949492,0.549841
26,Malta,27,6.527,1.343280,0.821944,0.588767
27,Uruguay,28,6.454,1.217560,0.719217,0.579392
28,Guatemala,29,6.454,0.872002,0.540240,0.531311
29,Panama,30,6.452,1.233748,0.706156,0.550027
...,...,...,...,...,...,...
125,Congo (Kinshasa),126,4.280,0.092102,0.191407,0.235961
126,Mali,127,4.190,0.476180,0.169366,0.306614
127,Ivory Coast,128,4.180,0.603049,0.048642,0.447706
128,Cambodia,129,4.168,0.601765,0.429783,0.633376
129,Sudan,130,4.139,0.659517,0.290921,0.014996
130,Ghana,131,4.120,0.667225,0.295638,0.423026
131,Ukraine,132,4.096,0.894652,0.575904,0.122975
132,Uganda,133,4.081,0.381431,0.217633,0.443186
133,Burkina Faso,134,4.032,0.350228,0.215844,0.324368
134,Niger,135,4.028,0.161925,0.268505,0.363659
135,Malawi,136,3.970,0.233442,0.315090,0.466915
136,Chad,137,3.936,0.438013,0.041135,0.162342
137,Zimbabwe,138,3.875,0.375847,0.196764,0.336384
138,Lesotho,139,3.808,0.521021,0.000000,0.390661
139,Angola,140,3.795,0.858428,0.049869,0.000000
140,Afghanistan,141,3.794,0.401477,0.180747,0.106180
141,Botswana,142,3.766,1.122094,0.341756,0.505196
142,Benin,143,3.657,0.431085,0.209930,0.425963
143,Madagascar,144,3.644,0.305809,0.375223,0.189197
144,Haiti,145,3.603,0.368610,0.277321,0.030370
145,Yemen,146,3.593,0.591683,0.310081,0.249464
146,South Sudan,147,3.591,0.397249,0.163486,0.147062
147,Liberia,148,3.533,0.119042,0.229918,0.332881
148,Guinea,149,3.507,0.244550,0.194129,0.348588
149,Togo,150,3.495,0.305445,0.247106,0.380426
150,Rwanda,151,3.471,0.368746,0.326425,0.581844
151,Syria,152,3.462,0.777153,0.500533,0.081539
152,Tanzania,153,3.349,0.511136,0.364509,0.390018
153,Burundi,154,2.905,0.091623,0.151611,0.059901
154,Central African Republic,155,2.693,0.000000,0.018773,0.270842

In [17]:
new_happiness_df = new_happiness_df.replace({"United States": "USA"})
new_happiness_df.head()

,Country,Happiness.Rank,Happiness.Score,Economy..GDP.per.Capita.,Health..Life.Expectancy.,Freedom
0,Norway,1,7.537,1.616463,0.796667,0.635423
1,Denmark,2,7.522,1.482383,0.792566,0.626007
2,Iceland,3,7.504,1.480633,0.833552,0.627163
3,Switzerland,4,7.494,1.564980,0.858131,0.620071
4,Finland,5,7.469,1.443572,0.809158,0.617951

In [18]:
new_happiness_df = new_happiness_df.rename(columns={"Country": "Country", "Happiness.Rank": "Happiness Rank", "Happiness.Score": "Happiness Score", "Economy..GDP.per.Capita.": "GDP per Capita", "Health..Life.Expectancy.": "Life Expectancy", "Freedom": "Freedom"})
new_happiness_df.head()

,Country,Happiness Rank,Happiness Score,GDP per Capita,Life Expectancy,Freedom
0,Norway,1,7.537,1.616463,0.796667,0.635423
1,Denmark,2,7.522,1.482383,0.792566,0.626007
2,Iceland,3,7.504,1.480633,0.833552,0.627163
3,Switzerland,4,7.494,1.564980,0.858131,0.620071
4,Finland,5,7.469,1.443572,0.809158,0.617951

In [19]:
merged_df = pd.merge( grouped_country, new_happiness_df,how='left', on='Country')
merged_df

,Country,Stars,Happiness Rank,Happiness Score,GDP per Capita,Life Expectancy,Freedom
0,Australia,3.138636,10,7.284,1.484415,0.843887,0.601607
1,Bangladesh,3.714286,110,4.608,0.586683,0.533241,0.478357
2,Brazil,4.350000,22,6.635,1.107353,0.616552,0.437454
3,Cambodia,4.200000,129,4.168,0.601765,0.429783,0.633376
4,Canada,2.243902,7,7.316,1.479204,0.834558,0.611101
5,China,3.421893,79,5.273,1.081166,0.741416,0.472788
6,Colombia,3.291667,36,6.357,1.070622,0.595028,0.477487
7,Estonia,3.500000,66,5.611,1.320879,0.695168,0.479131
8,Finland,3.583333,5,7.469,1.443572,0.809158,0.617951
9,Germany,3.638889,16,6.951,1.487923,0.798951,0.562511
10,Ghana,3.500000,131,4.120,0.667225,0.295638,0.423026
11,"Hong Kong S.A.R., China",3.801825,71,5.472,1.551675,0.943062,0.490969
12,Hungary,3.611111,75,5.324,1.286012,0.687763,0.175864
13,India,3.395161,122,4.315,0.792221,0.455428,0.469987
14,Indonesia,4.067460,81,5.262,0.995539,0.492346,0.443323
15,Japan,3.981605,51,5.920,1.416915,0.913476,0.505626
16,Malaysia,4.157595,42,6.084,1.291215,0.618784,0.402265
17,Mexico,3.730000,25,6.578,1.153184,0.709979,0.412730
18,Myanmar,3.946429,114,4.545,0.367111,0.397523,0.514492
19,Nepal,3.553571,99,4.962,0.479820,0.504131,0.440306
20,Netherlands,2.710526,6,7.377,1.503945,0.810696,0.585384
21,Nigeria,1.500000,95,5.074,0.783756,0.056916,0.394953
22,Pakistan,3.000000,80,5.269,0.726884,0.402048,0.235215
23,Philippines,3.329787,72,5.430,0.857699,0.468009,0.585215
24,Poland,3.625000,46,5.973,1.291788,0.699475,0.520342
25,Singapore,4.126147,26,6.572,1.692278,0.949492,0.549841
26,South Korea,3.790554,55,5.838,1.401678,0.900214,0.257922
27,Sweden,3.250000,9,7.284,1.494387,0.830875,0.612924
28,Taiwan Province of China,3.665402,33,6.422,1.433627,0.793984,0.361467
29,Thailand,3.384817,32,6.424,1.127869,0.647239,0.580201
30,USA,3.457948,14,6.993,1.546259,0.774287,0.505741
31,United Arab Emirates,3.583333,21,6.648,1.626343,0.726798,0.608345
32,United Kingdom,2.997101,19,6.714,1.441634,0.805336,0.508190
33,Vietnam,3.187963,94,5.074,0.788548,0.652169,0.571056

In [30]:
#create database connection
connection_string = "postgres:postgres@0.0.0.0:5432/ramen_db"
engine = create_engine(f'postgresql://{connection_string}')

In [31]:
engine.table_names()

OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "0.0.0.0" and accepting
	TCP/IP connections on port 5432?

In [29]:
merged_df.to_sql(name='ramen_happiness', con=engine, if_exists='append', index=True)

OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?